name: Rancher Workloads Redeploy Action
description: Rancher CD tool
runs:
  using: composite
  steps:
    - id: request
      name: Send request to Rancher
      shell: bash
      run: |
        curl --location --request POST "${API_ACCESS_ADDR}/project/${CLUSTER}:${PROJECT}/workloads/deployment:${NAMESPACE}:${WORKLOAD}?action=redeploy" \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --header "Authorization: Bearer ${RANCHER_TOKEN}"